spring:
  application:
    name: employee-dashboard-gateway
    
  cloud:
    gateway:
      routes:
      - id: employeeV1
        uri: http://localhost:8080
        predicates:
        - Path=/api/v1/employees/
        - Weight=group1, 4
      - id: employeeV2
        uri: http://localhost:8085
        predicates:
        - Path=/api/v2/employees/
        - Weight=group1, 6
    
server:
  port: 9000
    
eureka:
  client:
    register-with-eureka: false
